[project]
name = "dataexp"
version = "0.1.0-alpha.1"
description = "Lightweight Python library for quickly exploring a pandas DataFrame"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=3.0.5",
    "python-dateutil>=2.9.0.post0",
]

[dependency-groups]
dev = [
    "seaborn>=0.13.2",
]

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[project.urls]
repository = "https://github.com/XcelCh/dataexp"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true